textadventure_project/textadventure_app/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

app_name = "textadventure_app"

urlpatterns = [
    path('', views.index, name='index'),
    path('station/<str:station_name>_<str:spieler>', views.station, name='station'),
    path('save_inventar/<int:choice_id>_<int:spieler_id>', views.save_inventar, name='save_inventar'),
    path('choose_station/<int:choice_id>_<int:spieler_id>', views.choose_station, name='choose_station'),
    path('save_spieler', views.save_spieler, name='save_spieler'),
]

textadventure_project/textadventure_project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('textadventure_app/', include('textadventure_app.urls') ),
]

textadventure_project/textadventure_app/models.py
from django.db import models


class Station(models.Model):
    name = models.CharField(max_length=50, unique=True)
    title = models.CharField(max_length=200)
    text = models.TextField()
    required_inventar = models.CharField(max_length=200, blank=True)
    def __str__(self):
        return self.name


class Choice(models.Model):
    c_station = models.ForeignKey(to=Station, on_delete=models.CASCADE)
    text = models.CharField(max_length=200)
    next_station = models.ManyToManyField(Station, related_name="incoming_set", blank=True)

    def __str__(self):
        return f"{self.text}: {self.next_station.all()}"


class Inventar(models.Model):
    name = models.CharField(max_length=50)
    choice = models.ForeignKey(to=Choice, on_delete=models.CASCADE)

    def __str__(self):
        return self.name


class Spieler(models.Model):
    name = models.CharField(max_length=50, unique=True)
    station = models.ForeignKey(to=Station, on_delete=models.CASCADE)
    inventar = models.ManyToManyField(Inventar, blank=True)
    def __str__(self):
        return f"{self.name} {self.inventar.name}"

textadventure_project/textadventure_app/views.py
from django.shortcuts import render, get_object_or_404, get_list_or_404
from . import models
from django.urls import reverse
from django.http import HttpResponse, HttpResponseRedirect, HttpResponseNotFound


def index(request):
    spieler = models.Spieler.objects.all()
    context = {"spieler": spieler}
    return render(request, "textadventure_app/index.html", context)

def station(request, station_name, spieler):
    spieler = get_object_or_404(models.Spieler, name=spieler)
    station = get_object_or_404(models.Station, name=station_name) 
    spieler.station = station
    choices =  get_list_or_404(models.Choice, c_station__name=station_name)
    if station_name == "start":
        spieler.inventar.clear()
    spieler.station = station
    spieler.save()
    sentences = station.text.split(".")
    context = {"station": station, "spieler": spieler, "choices": choices, "sentences": sentences}
    return render(request, "textadventure_app/station.html", context)


def save_inventar(request, choice_id, spieler_id):
    inventar = models.Inventar.objects.get(choice=choice_id)
    spieler = models.Spieler.objects.get(id=spieler_id)
    spieler.inventar.add(inventar)
    inventar.save()
    spieler.save()
    choice = get_object_or_404(models.Choice,id=choice_id)
    for st in choice.next_station.all():
        name = st.name
    return HttpResponseRedirect(reverse('textadventure_app:station', args=[name, spieler.name,]))


def choose_station(request, choice_id, spieler_id):
    spieler = models.Spieler.objects.get(id=spieler_id)
    choice = get_object_or_404(models.Choice,id=choice_id)

    if choice.next_station.all():
        for st in choice.next_station.all():
            if st.required_inventar in spieler.inventar.values_list("name", flat=True):
                name=st.name
                break
            else:
                name = st.name
    else:
        spieler.delete()
        return HttpResponseRedirect(reverse('textadventure_app:index'))
        
    return HttpResponseRedirect(reverse('textadventure_app:station', args=[name, spieler.name,]))


def save_spieler(request):
    new_spieler = models.Spieler()
    new_spieler.name = request.POST.get("name")
    new_spieler.station = models.Station.objects.get(name="start")
    new_spieler.save()
    return HttpResponseRedirect(reverse('textadventure_app:station', args=[new_spieler.station, new_spieler.name,]))

textadventure_project/textadventure_app/templates/textadventure_app/index.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, shrink-to-fit=no">
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">
    <title>Spieler</title>
    <link rel="stylesheet" href="{% static 'textadventure_app/style.css' %}">
</head>
<body>
		<div class="overlay">
			
            <div class="container align-items-center mt-5 text-white">
                <div class="row justify-content-center">
                    <div class="col-lg-6 mt-3">
                        <h1 class="display-1 text-center">DIE NACHT</h1>
                        <hr class="bg-white">
                    </div>
                </div>
                <div class="row justify-content-center">
                    <div class="col-lg-4 text-center">
                        <form action="{% url 'textadventure_app:save_spieler' %}" method="post">
                            <div class="form-group m-3">
                            {% csrf_token %}
                                <label for="name">Neuer Spieler:</label>
                                <input type="text" class="form-control" id="name" name="name">
                                <button type="submit" class="btn btn-primary mt-3 text-light bg-dark" value="new_spieler">Spiel starten</button>
                            </div>
                        </form>
                        
                    </div>
                    
                </div>
                <br>
                
                <div class="row justify-content-md-center ">
                    <div class="col-lg-4 text-center">
                    <p>Spieler wählen:</p>
                    <table class="table text-center text-white ">
                        <thead>
                        <tr>
                            <th scope="col">Name</th>
                            <th scope="col">Fortsetzen</th>
                        </tr>
                        </thead>
                        <tbody>
                        <tr> 
                        {% for s in spieler %}
                            <th scope="row">{{s.name}}</th>
                            <td><a class="btn btn-primary ml-3 bg-dark" href="{% url 'textadventure_app:station' s.station.name s.name  %}" role="button">Spiel fortsetzten</a></td>
                        </tr>
                        {% endfor %}
                        </tbody>
                    </table>
                </div>
                </div>


            </div> 
            

  
		</div>
        
        <video loop muted autoplay poster="video/plane.jpg" class="fullscreen-bg__video">
            <source src="{% static 'textadventure_app/video.mp4' %}" type="video/mp4">
	    </video>



  




    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ho+j7jyWK8fNQe+A12Hb8AhRq26LrZ/JpcUGGOn+Y7RsweNrtN/tE3MoK7ZeZDyx" crossorigin="anonymous"></script>
</body>
</html>

textadventure_project/textadventure_app/templates/textadventure_app/station.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, shrink-to-fit=no">
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">
    <title>{{station.title}}</title>
    <link rel="stylesheet" href="{% static 'textadventure_app/style.css' %}">
</head>
<body>

<div class="overlay">

    <div class="container align-items-center mt-5 text-white">
        <div class="row">
            <div class="col-lg-3">
                <div class="card border-light bg-transparent">
                    <h5 class="card-header border-light">{{spieler.name}}</h5>
                    <div class="card-body border-light">
                      <h5>Inventar:</h5>
                      <ul class="list-group list-group-flush">
                        {% for item in spieler.inventar.all %}
                        <li class="list-group-item bg-transparent">- {{item.name}}</li>
                        {% endfor %}
                      </ul>
                        
                    </div>
                </div>
            </div>
        </div>
        <div class="row justify-content-center">
            <div class="col-lg-7 text-center">
                <h3 class="display-4 text-center">{{station.title}}</h1>
                <hr class="bg-white">
                {% for s in sentences%}
                <p>{{s}}.</p>
                {% endfor %}
                <br>
                {% for choice in choices %}
                    {% if choice.inventar_set.all %}
                        <a href="{% url 'textadventure_app:save_inventar' choice.id spieler.id  %}" class="btn btn-primary bg-dark">{{choice.text}}</a>
                    {% else %}
                        <a href="{% url 'textadventure_app:choose_station' choice.id spieler.id  %}" class="btn btn-primary bg-dark">{{choice.text}}</a>
                    {% endif %}
                {% endfor %}
            </div>
        </div>


</div>
        
<video loop muted autoplay poster="video/plane.jpg" class="fullscreen-bg__video">
    <source src="{% static 'textadventure_app/video.mp4' %}" type="video/mp4">
</video>

    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ho+j7jyWK8fNQe+A12Hb8AhRq26LrZ/JpcUGGOn+Y7RsweNrtN/tE3MoK7ZeZDyx" crossorigin="anonymous"></script>
</body>
</html>